layer.translucent = minecraft:glass minecraft:glass_pane minecraft:beacon
layer.cutout = minecraft:redstone minecraft:redstone_dust
#if MC_VERSION >= 11300
layer.solid minecraft:grass_block
#else
layer.solid minecraft:grass_block minecraft:grass
#endif