layer.translucent = minecraft:glass minecraft:glass_pane
layer.cutout = minecraft:redstone
#if MC_VERSION >= 11300
layer.solid minecraft:grass_block
#else
layer.solid minecraft:grass_block minecraft:grass
#endif