screen= [blocks] [entities] [particles] [stars] [weather] [hand]

screen.blocks = blocks_red blocks_green blocks_blue
screen.entities = entites_red entites_green entites_blue
screen.particles = particle_red particle_green particle_blue
screen.stars = star_red star_green star_blue
screen.weather = weather_red weather_green weather_blue
screen.hand = hand_red hand_green hand_blue

screen.columns = 3