screen = <profile> <empty> [general_settings] [blocks] [entities] [sky] [particles] [sun_and_moon] [stars] [weather] [hand] [clouds] [Translucent_blocks] [beacon_beams] [other] *

clouds = fancy

screen.general_settings = color_inversion_during_day_night cutout_blocks_are_inverted Do_DH_blocks_render
screen.blocks = blocks_red blocks_green blocks_blue
screen.entities = entites_red entites_green entites_blue
screen.sky = sky_red sky_green sky_blue
screen.particles = particle_red particle_green particle_blue
screen.sun_and_moon = sun_and_moon_red sun_and_moon_green sun_and_moon_blue
screen.stars = star_red star_green star_blue
screen.weather = weather_red weather_green weather_blue
screen.hand = hand_red hand_green hand_blue hand_invisible
screen.clouds = clouds_red clouds_green clouds_blue hide_clouds
screen.Translucent_blocks = Translucent_blocks_red Translucent_blocks_green Translucent_blocks_blue Translucent_blocks_translusency_addition Translucent_blocks_invert_colors
screen.beacon_beams = beacon_beams_red beacon_beams_green beacon_beams_blue
screen.other = other_red other_green other_blue

screen.columns = 3

profile.white_on_black = blocks_red=0 blocks_green=0 blocks_blue=0 sky_red=0 sky_green=0 sky_blue=0 entites_red=1 entites_green=1 entites_blue=1 particle_red=1 particle_green=1 particle_blue=1 sun_and_moon_red=1 sun_and_moon_green=1 sun_and_moon_blue=1 star_red=1 star_green=1 star_blue=1 weather_red=1 weather_green=1 weather_blue=1 Translucent_blocks_red=1 Translucent_blocks_green=1 Translucent_blocks_blue=1 hand_red=1 hand_green=1 hand_blue=1 beacon_beams_red=1 beacon_beams_green=1 beacon_beams_blue=1 other_red=1 other_green=1 other_blue=1
profile.black_on_white = blocks_red=1 blocks_green=1 blocks_blue=1 sky_red=1 sky_green=1 sky_blue=1 entites_red=0 entites_green=0 entites_blue=0 particle_red=0 particle_green=0 particle_blue=0 sun_and_moon_red=0 sun_and_moon_green=0 sun_and_moon_blue=0 star_red=0 star_green=0 star_blue=0 weather_red=0 weather_green=0 weather_blue=0 Translucent_blocks_red=0 Translucent_blocks_green=0 Translucent_blocks_blue=0 hand_red=0 hand_green=0 hand_blue=0 beacon_beams_red=0 beacon_beams_green=0 beacon_beams_blue=0 other_red=0 other_green=0 other_blue=0

sliders = blocks_red blocks_green blocks_blue entites_red entites_green entites_blue sky_red sky_green sky_blue particle_red particle_green particle_blue sun_and_moon_red sun_and_moon_green sun_and_moon_blue star_red star_green star_blue weather_red weather_green weather_blue Translucent_blocks_red Translucent_blocks_green Translucent_blocks_blue Translucent_blocks_translusency_addition hand_red hand_green hand_blue clouds_red clouds_green clouds_blue beacon_beams_red beacon_beams_green beacon_beams_blue other_red other_green other_blue