screen= <profile> <empty> <empty> [blocks] [entities] [particles] [stars] [weather] [hand]

screen.blocks = blocks_red blocks_green blocks_blue
screen.entities = entites_red entites_green entites_blue
screen.particles = particle_red particle_green particle_blue
screen.stars = star_red star_green star_blue
screen.weather = weather_red weather_green weather_blue
screen.hand = hand_red hand_green hand_blue

screen.columns = 3

profile.white_on_black = blocks_red=0 blocks_green=0 blocks_blue=0 entites_red=1 entites_green=1 entites_blue=1 particle_red=1 particle_green=1 particle_blue=1 star_red=1 star_green=1 star_blue=1 weather_red=1 weather_green=1 weather_blue=1 hand_red=1 hand_green=1 hand_blue=1
profile.black_on_white = blocks_red=1 blocks_green=1 blocks_blue=1 entites_red=0 entites_green=0 entites_blue=0 particle_red=0 particle_green=0 particle_blue=0 star_red=0 star_green=0 star_blue=0 weather_red=0 weather_green=0 weather_blue=0 hand_red=0 hand_green=0 hand_blue=0